url: figdigitalmarketing.com
baseurl: 

# Site settings
title: FIG Digital Marketing
email: chris@figdigitalmarketing.com
description: "FIG Digital Marketing is a digital marketing agency specializing in SEO, SEM, and more for small businesses."


# Team names, titles and social links
people:

- name: Chris Newton
  pic: 2
  position: Lead Marketer
  social:

    - title: linkedin
      url: https://www.linkedin.com/in/cnewton25/



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:



# Postal address (add as many lines as necessary)
address:
  - line: 2 Shaker Rd, Suite B211
  - line: Shirley, MA 01464

# Build settings
markdown: kramdown
permalink: pretty